# Generated by Django 2.0.3 on 2018-03-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_maestra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido_m',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido_p',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='fecha_nac',
            new_name='fecha_nacimiento',
        ),
    ]
